name: main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install xcbeautify
      run: brew install xcbeautify

    - name: Test
      run: set -o pipefail && xcodebuild clean test -project HomeBugh.xcodeproj -scheme HomeBugh -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' | xcbeautify

